### PR TITLE
Add meeting notes.

### PR DESCRIPTION
**Pull request by jdalton**

### CODE REVIEW

**Comment by MylesBorins** [comment]
@jdalton should this be added to https://github.com/nodejs/modules/pull/79 ?

**Comment by jdalton** [comment]
That was my intent. I figured that's how the other commit landed in there :P

**Comment by MylesBorins** [comment]
I have pushing to branches enable for collaborators. You should be able to just push to it :smile:

**Comment by jdalton** [comment]
Oh fancy! 💅

**Pull request closed without merging**
